dts/msm8916-motorola-harpia.dts
dts/rules.mk
platform/msm_shared/smem.c

Tested working on my Motorola Moto G4 Play (motorola-harpia).

dts: Add device tree for motorola-harpia

---

dts/msm8916-motorola-surnia.dts
dts/rules.mk

Tested, it booting, correct detected under Linux. Can boot other kernel properly.

msm8916: surnia: initial bringup to lk2nd

---

dts/msm8916-motorola-osprey.dts
dts/rules.mk

dts: motorola-osprey: Add support for the Motorola Moto G 2015

---

app/aboot/lk2nd-device.c

Fix some issues with panel detection

---

dts/msm8916/msm8916-huawei-hwt1a21l.dts
dts/msm8916/rules.mk

dts: Add Huawei Mediapad T1 A21L

---

dts/msm8916/msm8916-samsung-r04.dts

Adds Samsung Tab A 8.0 (msm8916) (gt58lte-eur)

Add SM-T355Y

---

dts/msm8916/msm8939-mtp.dts

PANEL - qcom,mdss_dsi_jdi_nt35595_1080p_video

dts: Add new panel Xiaomi Mi 4i (xiaomi-ferrari)

---

README.md
dts/msm8226/apq8026-asus-sparrow.dts
dts/msm8226/rules.mk

Works with @MartijnBraam 's watch now ;)
Also hacktoberfest label please :smile:

dts: msm8226: Add ASUS ZenWatch 2 (sparrow)

---

app/aboot/fs_boot.c
app/aboot/fs_boot.h
include/fs_boot.h
include/lk2nd.h
lk2nd/lk2nd-device.c
lk2nd/lk2nd-rproc.c
lk2nd/rules.mk
lk2nd/smp/spin-table.c
project/lk2nd-msm8916.mk

See https://gitlab.com/postmarketOS/pmaports/-/merge_requests/2632

Patch dtb to implement no-modem functionality

---

README.md
dts/msm8916/msm8916-samsung-r11.dts
dts/msm8916/rules.mk

[gprime-lk2nd.txt](https://github.com/msm8916-mainline/lk2nd/files/7465770/gprime-lk2nd.txt)

dts: Add Samsung Galaxy Grand Prime (SM-G530Y)

---

README.md
dts/msm8916/msm8916-qrd4-v1.dts
dts/msm8916/rules.mk

I tested it. It works on my device with nt35521 panel.

dts: msm8916: Add ARK Benefit A3 (peach)

---

app/aboot/fastboot-extra.c

Add fastboot oem commands to read/write a specified address.
Usage:
```
fastboot oem readl <address>
fastboot oem readb <address>
fastboot oem writel <address> <value>
fastboot oem writeb <address> <value>
```

aboot: fastboot-extra: Add "fastboot oem readl&writel&readb&writeb"

---

LICENSE
README.md

This is supposed to be a better introduction for lk2nd, without relying on too much inside knowledge.

README: Add better introduction and various clarifications

---

lk2nd/smp/cpu-boot.c
platform/msm8916/msm8916-clock.c

Doing a bit of hackary on msm8939 its possible to get both clusters and all eight cores booted.
msm8936/msm8939 comes in a big.LITTLE 2x4 A53 cluster configuration.
Each core has its own L1 cache
All four cores in a given cluster, share an L2 cache
BootROM needs to enable the L2 cache for the cluster the boot CPU lives in, however it does not enable for the second cluster.
msm8916 has these same L2 enable registers but since it has only one cluster, there's no need to take these specific steps to switch the L2 on for msm8916.
lk2nd as is, switches on four cores in the primary cluster for me via the spin-table hack.
This series then extends that out to all eight cores.
Reference DTS
cpus {
#address-cells = <1>;
#size-cells = <0>;
CPU0: cpu@100 {
device_type = "cpu";
compatible = …

master+msm8939 2nd cluster poweron

---

dts/msm8916/msm8916-samsung-r11.dts

v2: Rename to fortunaltezt ~~and add panel selection~~

dts: Rename SM-G530Y from gprimeltezt to fortunaltezt

---

lk2nd/panel/generated/lk_panel_booyi_otm1287_720p_video.h
lk2nd/panel/generated/panels.h

This can be used in sb-off seed devices or soc-swap'd crackling if someone has that :P

lk2nd: panel: generated: add booyi_otm1287 for seed

---

dts/msm8916/msm8216-samsung-r07.dts
dts/msm8916/msm8916-samsung-gprime.dtsi
dts/msm8916/msm8916-samsung-r02.dts
dts/msm8916/msm8916-samsung-r11.dts
dts/msm8916/msm8929-samsung-r04.dts
dts/msm8916/rules.mk

dts: msm8916: Add Samsung Galaxy Grand Prime (SM-G530H)

---

dts/msm8916/apq8016-samsung-r02.dts

Signed-off-by: Nick Reuter <nreuter85@gmail.com>
Change-Id: I8afdbe7df711b5d12fc3ccc08d4298440c379707

dts: add support for gt58wifi

---

doc/devicetree.md
doc/fastboot.md

Docs fixes

---

README.md
dts/msm8916/msm8929-qrd-wt82918.dts
dts/msm8916/rules.mk

Add Lenovo Vibe K5 (A6020a40)

---

README.md
dts/msm8226/apq8026-samsung-r03.dts
dts/msm8226/msm8926-samsung-r02.dts
dts/msm8226/rules.mk

Also known as Samsung Galaxy Tab 4 10.1 LTE.

msm8226: Add Samsung Galaxy Tab 4 10.1 (2014) (SM-T535)

---

README.md

Change-Id: If7a4149194eb2a0b16e9a05091fd6997adafc0e2

lk2nd: update the readme to reflect T-350 support

---

README.md
dts/msm8916/msm8916-512mb-mtp.dts
dts/msm8916/msm8916-mtp.dts

Also added lk2nd,match-cmdline for UFI-001C.

[Patch] Add support for another LTE dongle uz801-v3.0

---

README.md
dts/msm8916/msm8939-qrd-wt82918.dts
dts/msm8916/rules.mk

msm8939: Add Lenovo Vibe K5 Plus

---

README.md
dts/msm8916/msm8916-samsung-r00.dts

add surport of On7 (2015) G600S

add surport of On7 2015 G600S

---

README.md
dts/msm8226/msm8926-htc-memul.dts
dts/msm8226/rules.mk

In the current code the display is not drawn correctly, this is fixed through PR #299.

dts: msm8226: Add HTC One Mini 2 (memul)

---

README.md
dts/msm8916/msm8916-vivo-y21l.dts
dts/msm8916/rules.mk
lk2nd/panel/generated/lk_panel_orise8012a_tmfwvga_cmd.h
lk2nd/panel/generated/panels.h

dts: msm8916: Add Vivo Y21L

---

README.md
dts/msm8916/msm8216-samsung-r05.dts

Add Ukrainian version of Samsung Galaxy J5 2016

---

lk2nd/device/dts/msm8952/msm8956-mtp.dts
lk2nd/device/dts/msm8952/msm8976-qrd.dts
lk2nd/device/dts/msm8952/rules.mk
lk2nd/device/dts/msm8953/msm8953-huawei-milan.dts
lk2nd/device/dts/msm8953/msm8953-lenovo-kuntao.dts
lk2nd/device/dts/msm8953/msm8953-motorola-deen.dts
lk2nd/device/dts/msm8953/msm8953-motorola-potter.dts
lk2nd/device/dts/msm8953/msm8953-mtp.dts
lk2nd/device/dts/msm8953/msm8953-qrd.dts
lk2nd/device/dts/msm8953/msm8953-xiaomi-common.dts
lk2nd/device/dts/msm8953/msm8953-xiaomi-daisy.dts
lk2nd/device/dts/msm8953/msm8953-xiaomi-markw.dts
lk2nd/device/dts/msm8953/msm8953-xiaomi-vince.dts
lk2nd/device/dts/msm8953/rules.mk
lk2nd/device/dts/msm8953/sdm450-samsung-r04.dts
lk2nd/device/dts/msm8953/sdm450-samsung-r05.dts
lk2nd/device/dts/msm8953/sdm632-fairphone-fp3.dts
lk2nd/device/dts/msm8953/sdm632-motorola-ocean.dts
lk2nd/device/dts/msm8953/sdm632-mtp.dts

This pull request bring device trees from msm8953 lk2nd fork

[rebase-dts] Import DTS for MSM8953/MSM8956/MSM8976 devices

---

lk2nd/device/dts/msm8994/msm8992-lg-h815.dts
lk2nd/device/dts/msm8994/rules.mk

booting kernel, flashing and buttons are working

[experimental-tmp4] dts: msm8994: add LG G4 (h815)

---

lk2nd/device/dts/msm8974/rules.mk
lk2nd/device/dts/msm8974/victara.dts

I'm opening new PR because i couldn't change source branch. I applied CR fixes.
Original PR: #348

dts: msm8974: add support for Motorola Moto X 2014 2nd gen.

---

lk2nd/device/dts/msm8953/msm8953-xiaomi-vince.dts

Xiaomi Redmi 5 Plus (xiaomi-vince) is an qrd device.

dts: xiaomi-vince: fix dts issues

---

lk2nd/device/dts/msm8953/msm8953-xiaomi-markw.dts

dts: xiaomi-markw: fix board-id

---

lk2nd/device/dts/msm8953/sdm450-xiaomi-rosy.dts

Add missing panel selection for Redmi 5.

dts: msm8953: Add panel selection for Xiaomi Redmi 5 (rosy)

---

Documentation/devices.md
lk2nd/device/dts/msm8952/msm8917-xiaomi-riva.dts
lk2nd/device/dts/msm8952/msm8937-motorola-montana.dts
lk2nd/device/dts/msm8952/msm8937-xiaomi-land.dts
lk2nd/device/dts/msm8952/msm8940-xiaomi-santoni.dts
lk2nd/device/dts/msm8952/rules.mk

This PR adds support for:
- Moto G5S
- Redmi 3S
- Redmi 4X
- Redmi 5A

msm8952: Add support for couple msm8917/msm8937/msm8940 devices

---

Documentation/devices.md

Docs: devices: add Motorola Moto G6

---

README.md

[Minor spelling mistake, I win](https://github.com/user-attachments/assets/cdb85dda-bd05-4d58-969b-84b9bfad2158)

Minor spelling mistake in README.md

---

Documentation/devices.md
lk2nd/device/dts/msm8916/msm8916-samsung.dts

part 2
J510GN is close to J510F

dts: msm8916-samsung: Add support for another J5 2016 variant (j5xnltedx)

---

lk2nd/device/dts/msm8916/msm8916-samsung.dts

Link: https://lore.kernel.org/r/20240129143147.5058-1-raymondhackley@protonmail.com

dts: msm8916-samsung: fix grandprimelte dtb

---

lk2nd/device/dts/msm8916/msm8939-huawei-rio.dts

added panel for these devices  
panel driver will be push to the repo later

Huawei G7 Plus / G8 / GX8 / Maimang 4: add Panel

---

Documentation/devices.md
lk2nd/device/dts/msm8974/msm8974-blackberry-wolverine.dts
lk2nd/device/dts/msm8974/rules.mk

Hi all.
This PR adds support for the BlackBerry Passport (wolverine). 
Was tested on my personal device (European distribution).
Best regards
Igor

Add support for BlackBerry Passport

---

Documentation/devices.md
lk2nd/device/dts/msm8952/msm8956-xiaomi-hydrogen.dts
lk2nd/device/dts/msm8952/rules.mk

Add msm8956 based xiaomi-hydrogen support.

doc/dts: msm8952: Add Xiaomi Mi Max (hydrogen)

---

Documentation/devices.md
lk2nd/device/dts/msm8952/msm8937-mtp.dts

Add support for msm8937 based xiaomi-prada.

dts: msm8952: Add Xiaomi Redmi 4 (prada)

---

Documentation/devices.md
lk2nd/device/dts/msm8916/msm8916-samsung.dts

dts: msm8916-samsung: Add support for Samsung Galaxy E7 variant  (E700F)

---

Documentation/devices.md
lk2nd/device/dts/msm8952/msm8952-mtp.dts

add support for motorola-athene

add support for motorola-athene

---

lk2nd/device/dts/msm8916/msm8916-samsung.dts

Link: https://lore.kernel.org/r/20240129143147.5058-1-raymondhackley@protonmail.com

dts: msm8916-samsung: rename cprime to rossa

---

Documentation/devices.md
lk2nd/device/dts/msm8952/rules.mk
lk2nd/device/dts/msm8952/sdm439-nokia-panther.dts

* This requires flashing dtbo partition with this https://github.com/barni2000/dtbo-lk2nd/pull/3

dts: msm8952: add support for Nokia 4.2 (panther)

---

lk2nd/include/lk2nd/util/lkfdt.h
lk2nd/util/lkfdt.c

These are not used in lk2nd yet, but might come useful in the future.

lk2nd: util: lkfdt: Add more phandle helpers used in qebspil 
