- dts/msm8916-samsung-r06.dts
- dts/rules.mk
Added dts file for Galaxy Tab A 8.0, Canadian LTE version SM-T357W
> dts: Add Galaxy Tab A 8.0 (SM-T357W)

- app/aboot/aboot.c
make memcpy also copy null-terminator.
> aboot: add missing null-termination to return of concat_args

- README.md
- app/aboot/lk2nd-device.c
- app/aboot/lk2nd-device.h
- dts/msm8916/msm8916-asus-z00l.dts
- dts/msm8916/msm8916-motorola-harpia.dtsi
- dts/msm8916/msm8916-motorola-osprey.dts
- dts/msm8916/msm8916-motorola-surnia.dts
- dts/msm8916/msm8916-qrd12-v1.dts
- dts/msm8916/msm8916-qrd8-v1.dts
- dts/msm8916/msm8916-qrd9-v1.dts
- dts/msm8916/rules.mk
- platform/msm_shared/dev_tree.c
- platform/msm_shared/display_menu.c
Some devices have multiple possible panels. In that case, we need
to load different panel drivers. On downstream this is implemented
directly in the kernel, but this is difficult to implement cleanly
in mainline.
Instead, it's easier to do this as part of lk2nd. The mainline device
tree only contains a generic compatible (e.g. "motorola,harpia-panel")
with all required properties for it (e.g. GPIOs, regulators, ...).
We assume that the panels are similar enough that they all need exactly
the same properties.
The lk2nd device tree then contains a list of possible panels with
their mainline compatibles (e.g. "motorola,harpia-panel-tianma").
We can identify the panel using the "mdss_mdp.panel" parameter passed
by the primary bootloader.
When mainline is booted, we search for the "generic" …
> lk2nd: Introduce mainline panel selection 

- scripts/dtbTool
- scripts/mkbootimg
Due to the strange shebang in the script, the patche-shebang failed
when it was built on the Guix/Nix package manager. I fixed it.
> scripts: fix shebang

- lk2nd/smb1360/smb1360-qcom.c
Fixup underflow in usnigned int operation. Currently causing issues in battery detecting.
> lk2nd: smb1360: fix battery detection for longcheer l8910

- dts/msm8916/msm8916-qrd9-v1.dts
Added support for Android One Gen 2 SEED (Longcheer L8150) phones like the i-Mobile IQ II android one phone.
> Add support for Android One Gen 2 SEED (Longcheer L8150)

- dts/msm8916/msm8916-samsung-r02.dts
- dts/msm8916/msm8929-samsung-r04.dts
- include/lk2nd.h
- lk2nd/lk2nd-device.c
- platform/msm_shared/dev_tree.c
- platform/msm_shared/display_menu.c
- platform/msm_shared/include/dev_tree.h
Implements and fixes #60 
**Testing:**
To test:
- Check lk_log (`fastboot oem lk_log && fastboot get_staged <some-file>.txt`)
- Check display menu (`fastboot oem screenshot && fastboot get_staged /dev/stdout | convert - lk2nd.png`)
- Test if `fastboot boot`ing lk2nd from lk2nd is possible
- Test if booting some downstream kernel is possible (e.g. TWRP)
> lk2nd: Implement more sophisticated DTB override mechanism

- platform/msm_shared/display_menu.c
The current on-screen instructions "Press volume key to select, and press power key to select" don't really clarify how to navigate and select an option. I'd suggest the following text to replace it: "Press volume keys to navigate, and press power key to select"
> Improve on-screen instructions

- dts/msm8916/msm8916-samsung-r00.dts
- dts/msm8916/rules.mk
Fixes bugs that prevented stock android kernel from loading
> dts: gt58lte-aus: fix incorrect id's from bootloader

- README.md
- dts/msm8916/msm8939-htc-m8qlul.dts
This adds support for htc-m8qlul (or htc-m8ql_ul), also known as HTC One M8s.
This doesn't actually work! But it does. You need to disable all other dts and then it works. If you don't, the device will go to its own fastboot instead of lk2nd after you boot. Minecrell suggested we merge it like this and do something more proper when/if I get mainline Linux booting on this thing.
> dts: htc-m8qlul: Add support for HTC One M8s

- dts/msm8916/msm8939-htc-m8qlul.dts
I notice the layout is the same as https://github.com/msm8916-mainline/lk2nd/blob/master/dts/msm8916/msm8916-lg.dts#L28, but I'm not sure this is worth generalising.
> htc-m8qlul: fix volume and power keys, add licence identifier 

- README.md
- dts/msm8916/msm8916-huawei-y635-l01.dts
- dts/msm8916/rules.mk
The phone will not boot lk2nd with **some** dtbs enabled, just like the [htc-m8qlul](https://github.com/msm8916-mainline/lk2nd/pull/78), so in order to fix this all other dtbs (or just msm8916-mtp.dts as of now) need to be disabled in [rules.mk](https://github.com/ungeskriptet/lk2nd/blob/master/dts/msm8916/rules.mk).
> dts: huawei-y635-l01: Add support for Huawei Y635-L01

- README.md
- dts/msm8916/msm8916-samsung-r06.dts
[e7000_lk2nd.img.dts.txt](https://github.com/msm8916-mainline/lk2nd/files/7213854/e7000_lk2nd.img.dts.txt)
[e7000_lk2nd.img.txt](https://github.com/msm8916-mainline/lk2nd/files/7213855/e7000_lk2nd.img.txt)
> dts: Add Samsung Galaxy E7 (SM-E7000)

- dts/msm8226/apq8026-lg-lenok.dts
- dts/msm8226/rules.mk
Rename lge to lg as requested by Linux maintainers.
> msm8226: rename vendor of apq8026-lge-lenok

- include/sys/types.h
There is a build error when compiling lk2nd in Alpine Linux environment:
```
In file included from include/platform/debug.h:26,
from include/debug.h:31,
from target/msm8916/init.c:29:
include/sys/types.h:41:23: error: conflicting types for 'size_t'
41 | typedef unsigned long size_t;
|                       ^~~~~~
In file included from /usr/include/stddef.h:17,
from include/sys/types.h:27,
from include/platform/debug.h:26,
from include/debug.h:31,
from target/msm8916/init.c:29:
/usr/include/bits/alltypes.h:43:24: note: previous declaration of 'size_t' was here
43 | typedef unsigned _Addr size_t;
|
```
This is related to musl-libc specific type sizes for 32-bit architectures.
Good thing is that we don't need to redefine size_t at all. We can use
musl-specific define: `__DEFINED_size_t` to …
> Detect size_t in a way that is compatible with musl-libc

- README.md
- dts/msm8974/msm8974-lge-hammerhead.dts
- dts/msm8974/rules.mk
- platform/msm_shared/dev_tree.c
- platform/msm_shared/include/dev_tree.h
A possible solution to [pmaports#1227
](https://gitlab.com/postmarketOS/pmaports/-/issues/1227)
pmOS and TWRP are able to boot on ``androidboot.hardware.ddr=elpida`` devices with this dts. But not on ``androidboot.hardware.ddr=hynix`` devices.
Closes #96
> dts: Add LG Google Nexus 5 D820 and D821 (hammerhead)

- app/aboot/aboot.c
- platform/msm_shared/display_menu.c
Motorola has all these weird device configuration values (bootloader version, radio, carrier, ...) that are not too clear sometimes. Display them for debugging on the fastboot screen. Previously only bootloader version was shown.
> Display Motorola radio/carrier on display menu

- README.md
- dts/msm8916/msm8929-samsung-r04.dts
- dts/msm8916/msm8939-samsung-r01.dts
- dts/msm8916/rules.mk
```
~$ fastboot oem dump-smd-rpm
(bootloader) ch4: rpm_requests, cid: 0x4, flags: 0x20f, ref: 1
(bootloader) ch4: tx state: 0, tx fstate: 0, rx state: 4, rx fstate: 1
(bootloader) ch5: rpm_requests, cid: 0x5, flags: 0x210, ref: 1
(bootloader) ch6: rpm_requests, cid: 0x6, flags: 0x212, ref: 1
(bootloader) ch7: rpm_requests, cid: 0x7, flags: 0x213, ref: 1
OKAY [  0.006s]
Finished. Total time: 0.006s 
```
`lk2nd,smd-rpm-hack-opening;` is required to boot mainline. Otherwise the screen goes pitch black and no sign of further booting.
> dts: Add Samsung Galaxy A7 2015 (SM-A700YD)

- include/lk2nd.h
- lk2nd/lk2nd-device.c
- lk2nd/lk2nd-fdt.c
- lk2nd/lk2nd-rproc.c
- lk2nd/rules.mk
- lk2nd/smp/cpu-boot.c
- lk2nd/smp/cpu-boot.h
- lk2nd/smp/spin-table.c
Add support for using the spin-table code to boot the CPUs in ARM32 mode instead of ARM64. This is typically not needed/usable without modifications in Linux ARM32 (since it uses custom SMP boot code that is already upstream). But it's still useful when booting something other than Linux for example (to avoid having to copy the CPU boot code).
The way this works at the moment is that spin table is skipped if the `/psci` device tree node is already disabled (which is the case on ARM32 Linux). Otherwise it's set up as usual. It also works on devices with 32-bit TZ.
> lk2nd: smp: spin-table: Add support for ARM32

- platform/msm_shared/dev_tree.c
Downstream device trees contain bootargs = "sched_enable_hmp=1".
The original intention was that this would get prepended to the real
command line. However, this currently only works with a modification
in libfdt (see 5ac5542029fa0706829a30247445a998ad6cb93c) and has
therefore been broken since the libfdt update. Booting downstream was
effectively broken because the proper cmdline was missing.
Instead of modifying libfdt, fix this properly by replacing the null
terminator with a space.
Might fix #121
> dev_tree: Fix appending cmdline if "bootargs" is already in DT

- README.md
- dts/msm8916/msm8916-samsung-r05.dts
This PR adds support for the Samsung Galaxy J5 2015 (SM-J500M). Check #134 for more info.
> dts: msm8916: Added support for SM-J500M

- app/aboot/fastboot-extra.c
- target/target_display_cont_splash_mdp5.c
These changes reduce the lag with screen updates on command mode displays by using an extra thread. Also, a `fastboot oem display-auto-refresh` is added to explicitly enable the auto refresh feature in the hardware for command mode displays. Unfortunately, we cannot enable it by default at the moment since it seems unreliable on some panels and/or MSM8974.
> Improve behavior for command mode displays

- app/aboot/fastboot-extra.c
Example output for Krait (MSM8974):
```
(bootloader) ID_PFR0 = 0x1031
(bootloader) ID_PFR1 = 0x10021
(bootloader) ID_DFR0 = 0x2011555
(bootloader) ID_AFR0 = 0x0
(bootloader) ID_MMFR0 = 0x10211104
(bootloader) ID_MMFR1 = 0x40000000
(bootloader) ID_MMFR2 = 0x1232000
(bootloader) ID_MMFR3 = 0x102211
(bootloader) ID_ISAR0 = 0x2101110
(bootloader) ID_ISAR1 = 0x13112111
(bootloader) ID_ISAR2 = 0x21232141
(bootloader) ID_ISAR3 = 0x11112131
(bootloader) ID_ISAR4 = 0x11142
(bootloader) ID_ISAR5 = 0x0
```
Example output for Cortex-A53 (MSM8916):
```
(bootloader) ID_PFR0 = 0x131
(bootloader) ID_PFR1 = 0x11011
(bootloader) ID_DFR0 = 0x3010066
(bootloader) ID_AFR0 = 0x0
(bootloader) ID_MMFR0 = 0x10101105
(bootloader) ID_MMFR1 = 0x40000000
(bootloader) ID_MMFR2 = 0x1260000
(bootloader) ID_MMFR3 = …
```
> fastboot-extra: Add "fastboot oem dump-cpuid" to dump CPU information

- dts/lk2nd.h
- dts/msm8226/apq8026-huawei-sturgeon.dts
- include/lk2nd.h
- target/target_keys_lk2nd.c
Allows entering fastboot mode on the Huawei Watch using the (single) power button.
> dev_tree: Allow mapping power key

- README.md
- dts/msm8974/msm8974pro-ab-pm8941-mtp.dts
- dts/msm8974/rules.mk
~~Volume down button doesn't work - #37~~
`fastboot boot` lk2nd from lk2nd doesn't work (booting TWRP works fine)
booting mainline also seems to have some problems iirc?
The rest works fine :)
> msm8974: Add support for Fairphone 2

- app/aboot/fastboot-msm8974.c
Loosely based on lk2nd implementation for msm8916 and on Linux mainline
get_krait_bin_format_b.
Example output:
```
$ fastboot oem dump-speedbin
(bootloader) PVS valid: 1, Redundant fuse select: 0
(bootloader) Speed bin: 1, PVS: 12, PVS version: 1 (speed1-pvs12-v1)
```
@minlexx Would be great if you could also test this on some devices that you have (especially 8974-AC if possible). So far I've only seen speed bin 1, different PVS (2, 8, 9, 10, 12, 13) and different PVS version (0, 1). 8974-AC should be speed bin 3.
> Implement oem dump-speedbin for msm8974

- lk2nd/panel/generated/lk_panel_r69431_720p_video.h
- lk2nd/panel/generated/panels.h
This is another possible panel for wingtech-wt88047.
To build lk1st with this, use:
```
make TOOLCHAIN_PREFIX=arm-none-eabi- lk1st-msm8916 \
LK1ST_DTB=msm8916-qrd7+12-v1 LK1ST_COMPATIBLE=wingtech,wt88047 \
LK1ST_PANEL=r69431_720p_video
```
This is a replacement for #109 with the panel header generated using [linux-mdss-dsi-panel-driver-generator] and integrated into the new lk1st configuration.
@fxsheep Since I have no way to test this (I have a different panel in my wt88047), I'm only going to merge it if you can test and confirm that it works correctly. Not sure if you still have any use for this.
[linux-mdss-dsi-panel-driver-generator]: https://github.com/msm8916-mainline/linux-mdss-dsi-panel-driver-generator
> lk2nd: panel: generated: Add r69431_720p_video for wingtech-wt88047

- app/aboot/fs_boot.c
- lib/partition/partition.c
- platform/msm8226/include/platform/iomap.h
- target/msm8226/init.c
Rework the msm8226 mmc init to also bring up the sdcard (in the same way as it is done on msm8916)
> target: msm8226: Enable sdcard fs support

- README.md
- dts/msm8226/msm8226-samsung-ms013g.dts
- dts/msm8226/rules.mk
This PR adds support for Samsung Galaxy Grand 2(SM-G7102).
> Add support for Samsung Galaxy Grand 2(SM-G7102)

- README.md
- dts/msm8226/msm8926-huawei-g6-l11-vb.dts
- dts/msm8226/rules.mk
This patch adds minimal support for the MSM8926-based Huawei G6 4G (G6-L11).
The MSM8926 SoC being very close to MSM8226, I believe it does not need its own make target at this point.
> dts: msm8226: Add Huawei G6-L11

- dts/msm8916/msm8916-samsung-r08.dts
- dts/msm8916/msm8916-samsung-r11.dts
- dts/msm8916/msm8929-samsung-r04.dts
The latest revision of SM-A500YZ (a5ltezt) should be r11.
Move it to msm8916-samsung-r11.
> dts: msm8916: a5ltezt: move to msm8916-samsung-r11

- app/aboot/aboot.c
- dts/msm8974/msm8974pro-ac-pm8941-mtp.dts
- dts/msm8974/rules.mk
- lk2nd/lk2nd-device.c
- project/lk2nd-msm8974.mk
This device needs to use lk2nd-appended-dtb.img, the other one fails with 'dtb not found'.
---
Not sure if we should call this "msm8974" or "msm8974pro". Linux now has both file names and compatibles adjusted for Snapdragon 801 (vs 800) devices to use msm8974pro. Shall we follow with this here?
> dts: msm8974: Add OnePlus One

- dts/msm8974/msm8974pro-ac-pm8941-mtp.dts
- dts/msm8974/sony/dsi-panel-leo.dtsi
- dts/msm8974/sony/msm8974-display-stubs.dtsi
- dts/msm8974/sony/msm8974pro-ac-shinano_leo-display.dtsi
- dts/msm8974/sony/msm8974pro-ac-shinano_leo_common.dtsi
The bootloader seems to use the dts of the boot partition to initialize
the panel, so a bunch of panel dts is included here.
---
Unfortunately booting something from lk2nd doesn't seem to work, it just boots into "S1 Service" which seems to be some kind of crashdump mode (among others). Also e.g. `fastboot oem lk_log && fastboot get_staged /dev/stdout` just hangs (at the get_staged command)
Others work just fine though:
```
$ fastboot oem dump-speedbin
(bootloader) PVS valid: 1, Redundant fuse select: 0
(bootloader) Speed bin: 3, PVS: 5, PVS version: 1 (speed3-pvs5-v1)
```
Maybe some buffer is smaller on this device compared to other msm8974? (side note but I also saw super weird behavior in the scratch buffer on msm8226 htc-memul so seems some OEMs love modifying core stuff)
> dts: msm8974: Add Sony Xperia Z3

- README.md
busybox tar doesn't unrecognize option sort=name.
Add GNU tar into the dependencies in addition.
> README.md: Building: Add Alpine Linux and postmarketOS dependencies

- app/aboot/aboot.c
Copy the relevant code from aboot_init function so fs-boot also works in this case also.
> app: aboot: Also try fsboot with "fastboot continue"

- target/msm8916/meminfo.c
256 MiB is too big for some low-memory devices and cause crashes.
Tested on a LTE dongle.
Resolve #239
> target: msm8916: meminfo: reduce max download size to 192 MiB

- dts/msm8974/msm8974-samsung-r14.dts
- lk2nd/lk2nd-device.c
Add support for overwriting panel compatible for Samsung Galaxy S5 for 2nd variation of the panel.
Default is considered to be s6e3fa2; add support for detecting ea8064g.
This is needed to submit panel drivers to mainline, as upstream requires them to be separate and not one combined driver.
> dts: msm8974: samsung-klte: panel selection

- dts/msm8916/msm8916-samsung-r11.dts
Add dts support for galaxy a5u canbmc (a500w)
its just a5u with different firmware, picks strange dts tho.
[downstream dts](https://github.com/Galaxy-MSM8916/android_kernel_samsung_msm8916/blob/lineage-17.1/arch/arm/boot/dts/samsung/msm8916/msm8916-sec-a5u-canbmc-r01.dts)
> dts: msm8916: Add Galaxy A5U CAN (SM-A500W)

- dts/msm8916/apq8016-samsung-r05.dts
lk2nd used to boot the wrong dtb and downstream wouldnt work
tested with lineageos19.1 on canadian gtelwifiue (although afaik theres no differences between the firmwares bootloaders)
> dts: apq8016: Fix downstream booting (gtelwifiue)

- dts/msm8974/msm8974pro-ac-pm8941-mtp.dts
The previous match-cmdline wasn't correct since the bootloader actually doesn't set androidboot.hardware=bacon in the cmdline. Let's match with the panel instead.
> dts: msm8974: Fix matching OnePlus One

- README.md
- dts/msm8916/msm8916-samsung-r11.dts
it is likely an china variant or a hk variant of a5 because there are seem to be only hk and cn version of stock firmw
are for it. 
[build.prop.txt](https://github.com/msm8916-mainline/lk2nd/files/11614522/build.prop.txt)
There are 2 code name beibg found in the /system/build.prop (a5ltechn and a5ltezc) of the stock rom 
a5ltechn should be the code name of it bc the hostname of the stock rom is a5ltechn
> dts: Add Samssung A5 (Duos) (SM-A5000)

- dts/msm8916/msm8916-512mb-mtp.dts
This series of devices shares the same board-id and kernel command line arguments with ufi-001c, so the support for them is on top of ufi-001c.
WPS button is not tested because mine doesn't have one, but I think it probably works. Tested both on MF601SL(lk2nd, lk1st) and UFI-001C(lk1st).
> dts: msm8916: msm8916-512mb-mtp: Add 4G modem stick mf601xx variants

- README.md
- dts/msm8226/msm8926-v2-720p-mtp.dts
- dts/msm8226/rules.mk
Tried with downstream kernel, vol-down gets into fastboot mode.
~TODO: add gpio definition for HOME button.~
> dts: msm8926: add support for Coolpad 8730L

- README.md
- dts/msm8916/msm8916-asus-z00e.dts
- dts/msm8916/rules.mk
adapted from Asus z00l, and changed the 2nd panel to one that my unit has, as first panel from z00l is found on z00e aswell.
> dts: msm8916: add support for Asus ZE500KL

- README.md
- dts/msm8916/msm8939-huawei-kiwi.dts
- dts/msm8916/msm8939-huawei-rio.dts
- dts/msm8916/rules.mk
Adds support for the Huawei G8/GX8. Tested with (RIO-L01).
Removed some board-id entries from `kiwi` that are now conflicting with `rio` .
For reference I mentioned the files in Huawei's downstream kernel sources containing those IDs.
> Huawei GX8 (RIO-L01)

- dts/msm8916/msm8916-qrd7+12-v1.dts
The stock Kitkat bootloader selects qrd/7-v1.1.
Cc: @TravMurav
> dts: msm8916: qrd/7+12-v1: Also match qrd/7-v1.1

- README.md
- dts/msm8226/apq8026-samsung-r09.dts
- dts/msm8226/rules.mk
Very similar to the existing SM-T530 support, but went with a separate dts file for clarity.
Couldn't find documentation on how the `-r*` suffixes are chosen for `dts` files, so I just incremented it for Samsung. Let me know if it should be something else.
> dts: Add support for Samsung Tab A 8.0 2014

- lk2nd/target_display_cont_splash_mdp5.c
Port over the functionality from experimental-tmp2 branch to read format from framebuffer so that screen works correctly on e.g. msm8926-htc-memul:
[300] Continuous splash detected: pipe: 1, base: 0x10a2d000, stride: 1440, source: 720x1280 (0,0), output: 720x1280 (0,0), format: 0x22216 (bpp: 2) (cmd mode: 0)
Just tested on htc-memul, should be also tested on other devices. Also not sure of the potential impacts on other devices really.
> target/display_cont_splash_mdp5: Backport format/bpp improvements

- README.md
- dts/msm8916/msm8916-samsung-r03.dts
I don't know anything about Linux kernel internals, but was able to get this working.
> add support for the Samsung Galaxy On7 2015 (SM-G600FY)

- README.md
- dts/msm8974/msm8974-samsung-r10.dts
The Chinese editions of Galaxy S5 (kltechn) are customized for all 3 carriers in China at that time, but currently only the Unicom one is tested and added.
Add the other two carrier editions.
Tested-by: Icenowy Zheng <uwu@icenowy.me> # for Telecom
==================
Test for G9008 is wanted, if @xtexChooser could do this thus thanks.
> dts: msm8974: add other carrier variants of kltechn

- README.md
- dts/msm8916/msm8216-samsung-r05.dts
J5 2016 3G (SM-J510H) doesn't support NFC, thus j5x+3g.
> dts: msm8916: samsung-j5x3gjv: rename from j5xn3g

- lk2nd/device/dts/msm8953/msm8953-xiaomi-vince.dts
Set back touchscreen-compatible to syna,rmi4-i2c because this is the primarily supported.
I would keep novatek compatible as a comment let users to switch it if they needed it.
> dts: xiaomi-vince: set back rmi4 as default touchscreen

- Documentation/devices.md
- lk2nd/device/dts/msm8952/msm8937-motorola-cedric.dts
- lk2nd/device/dts/msm8952/rules.mk
For some reason lk2nd fails to boot if `$(LOCAL_DIR)/msm8937-mtp.dtb` is included in `rules.mk`.
> dts: msm8952: Add Motorola Moto G5 (cedric)

- lk2nd/device/dts/msm8974/msm8974-lge-hammerhead.dts
- lk2nd/device/dts/msm8974/rules.mk
Assuming qcom,msm-id = <QCOM_ID_MSM8974 0x96 0x20002 0xb> is correct and
compatible with both D820 and D821, overrides are no longer required.
Drop the overrides, use lk2nd,match-bootloader = "HHZ*" instead of
lk2nd,match-cmdline and simplify the device tree.
To fix "dtb not found" error when doing `fastboot boot` with downstream
`boot.img` or `lk2nd-msm8974.img` when lk2nd expects appended DTBs
(ADTBs), and model "Unknown (FIXME!)" when ADTBs are load, add the dtb to
ADTBs rules. Fixes https://github.com/msm8916-mainline/lk2nd/issues/371.
> dts: msm8974-lge-hammerhead: drop msm-id overrides

- Documentation/fastboot.md
- lk2nd/device/device.c
- lk2nd/device/device.h
- lk2nd/fastboot/dtb.c
- lk2nd/fastboot/rules.mk
This allows inspecting the changes to the dtb made by the bootloader.
Usage: "fastboot oem dtb && fastboot get_staged output.dtb"
Fixes #372
> lk2nd: fastboot: Add "fastboot oem dtb" to dump dtb passed by bootloader

- Documentation/devices.md
- lk2nd/device/dts/msm8953/apq8053-lenovo-cd-18781y.dts
- lk2nd/device/dts/msm8953/rules.mk
Menu navigation is currently not possible as the only two buttons available on this device are Volume Up and Volume Down. Menu items can be browsed but not selected as there is no button mapped to KEY_HOME.
Note that bootloader unlock is not functional on the ThinkSmart View. But the device will boot any image as long as it is AVB1 signed. For simple and quick signing `magiskboot sign` can be used on `lk2nd.img`.
> dts: msm8953: Add Lenovo ThinkSmart View (CD-18781Y)

- lk2nd/device/dts/msm8916/msm8916-samsung.dts
- lk2nd/device/dts/msm8916/msm8929-samsung.dts
In the transfer from the old way of working to the new one, the match-bootloader line for on7lte-chn got mangled.
Retested a bit with removing the line from msm8929 and now it seems to work weirdly enough. Don't know what happened there when I got lk2nd working....
> on7lte-chn fixes

- Documentation/devices.md
- lk2nd/device/dts/msm8953/msm8953-asus-zenfone3.dts
- lk2nd/device/dts/msm8953/rules.mk
both ZE520KL and ZE552KL are using the same device tree on the downstream kernel, at least that's when I'm looking at the kernel source at the LineageOS.
---
btw, I have a question about `lk2nd.dtb-files`
```
lk2nd,dtb-files = "msm8953-asus-zenfone3", "ze552kl-sr1_msm8953-mtp";
```
the first one I followed the mainline kernel convention, while the second one is from the downstream kernel. Wdyt? Without these, the lk2nd still boots normally, though.
> dts: msm8953: Add Asus Zenfone 3 ZE520KL/ZE552KL (zenfone3)

- Documentation/devices.md
- lk2nd/device/dts/msm8952/msm8937-nokia-ple.dts
- lk2nd/device/dts/msm8952/rules.mk
Adds <i>some</i> support for the HMD Global Nokia 6 (ple).
The only weird thing I've noticed is that the volume keys are swapped around.
<i>The IDs seem to be correct, but still can't boot the downstream.</i>
Tried both, ADTB and QCDTB, but the result seems to be the same.
[lk2nd.log](https://github.com/user-attachments/files/16437903/lk2nd.log)
> dts: msm8952: Add support for HMD Global Nokia 6

- Documentation/devices.md
- lk2nd/device/dts/msm8952/msm8937-huawei-aum.dts
- lk2nd/device/dts/msm8952/rules.mk
Adds <i>some initial</i> support for the Huawei Honor 7C (aum-l41).
The main issue is that it has separate ramdisk and kernel partitions in place of a normal boot partition. And so, there's a need for some more shenanigans to make it work correctly.
<s><i>Haven't tested if it actually boots anything yet.</i></s>
<s>Trying to boot the downstream results in a freeze, whether it's flashed onto a new boot partition or booted without flashing.</s>
[lk2nd.log](https://github.com/user-attachments/files/16431450/lk2ndaum.log)
> dts: msm8952: Add support for Huawei Honor 7C

- lk2nd/device/dts/msm8953/msm8953-asus-zenfone3.dts
Actually, the mainline kernel needs this to identify the appropriate driver to use.
> dts: msm8953: add panel support for zenfone3

- lk2nd/device/dts/msm8953/apq8053-lenovo-cd-18781y.dts
Mainline settled on using the focaltech,ft8201 format instead of the edt prefix for LCMs that aren't actually made by EDT.
Link: https://lore.kernel.org/linux-input/20240804031310.331871-1-felix@kaechele.ca/T/
> dts: apq8053-lenovo-cd-18781y: change touchscreen-compatible for FT8201

- Documentation/devices.md
- lk2nd/device/dts/msm8952/msm8940-oppo-a57.dts
- lk2nd/device/dts/msm8952/rules.mk
- lk2nd/device/dts/msm8953/msm8953-oppo-r9s.dts
- lk2nd/device/dts/msm8953/rules.mk
These devices were released during which the official notice from CCP regarding locking down bootloader unlock access was released, so earlier versions of their bootloaders weren't impossible to crack, but requires some hacks to work. Please check the individual dts files. Thanks.
> Add support for OPPO MSM8937 devices

- Documentation/devices.md
- lk2nd/device/dts/msm8953/rules.mk
- lk2nd/device/dts/msm8953/sdm450-xiaomi-rosy.dts
This PR adds support for the Xiaomi Redmi 5 (rosy) which is an SDM450 (MSM8953) device. Unfortunately, I don't have a screen on this phone, so I can't add/test panel support.
<details>
<summary>lk2nd.log</summary>
```text
[0] welcome to lk
[10] platform_init()
[10] target_init()
[20] MMC card: <removed> (0.3, 05 1998), manufacturer: 15, OEM: 100, capacity: <removed> bytes
[30] SDHC Running in HS400 mode
[40] Done initialization of the card
[40] Waiting for the RPM to populate smd channel table
[40] lk2nd_init()
[50] Booted @ 0x80008000, r0=0x0, r1=0x0, r2=0x83400000
[50] Found valid DTB with 732 bytes total
[50] Command line from previous bootloader: lk2nd androidboot.emmc=true androidboot.verifiedbootstate=orange androidboot.veritymode=enforcing androidboot.keymaster=1 …
```
> dts: msm8953: Add support for Xiaomi Redmi 5 (rosy)

- lk2nd/device/dts/msm8953/msm8953-asus-zenfone3.dts
this PR updates the zenfone3 panel names for this feedback below
https://github.com/msm8953-mainline/linux-panel-drivers/pull/14#discussion_r1730397406
> dts: msm8953: zenfone3: update panel compatibles

- lk2nd/device/dts/lk2nd.dtsi
- lk2nd/device/dts/msm8953/rules.mk
- lk2nd/device/dts/msm8953/sdm450-motorola-ali.dts
- lk2nd/device/dts/rules.mk
Adds a device tree for the Motorola Moto G6.
The bootloader requires every appended device tree has the `model` property, otherwise it will crash trying to select a device tree. 
We could add proper model props to every device tree under msm8953, or just add an empty string model to `skeleton64.dtsi`?
`msm8952`'s `cedric` is also affected by this quirk.
> dts: msm8953: Add support for Motorola Moto G6

- lk2nd/device/dts/msm8952/msm8937-mtp.dts
> dts: msm8952: Add support for Lenovo K5 Play

- Documentation/devices.md
- lk2nd/device/dts/msm8952/msm8937-motorola-jeter.dts
- lk2nd/device/dts/msm8952/rules.mk
Add device tree for the Motorola Moto G6 Play (jeter).
> dts: msm8952: Add support for Motorola Moto G6 Play (jeter)

- Documentation/devices.md
- lk2nd/device/dts/msm8952/msm8917-mtp.dts
- lk2nd/device/dts/msm8952/msm8917-xiaomi-riva.dts
- lk2nd/device/dts/msm8952/msm8940-mtp.dts
- lk2nd/device/dts/msm8952/rules.mk
- Update xiaomi-riva's msm-id to use predefined id macros.
- Add xiaomi-ugglite (msm8917) and ugg (msm8940).
> Add support for Redmi Note 5 and Note 5 Prime

- lk2nd/display/panel/generated/lk_panel_ili9881c_hd_video.h
```
In file included from lk2nd/display/panel/generated/panels.h:8:
lk2nd/display/panel/generated/lk_panel_ili9881c_hd_video.h:813:28: warning: 'ili9881c_hd_video_off_command' defined but not used [-Wunused-variable]
813 | static struct mipi_dsi_cmd ili9881c_hd_video_off_command[] = {
|
```
> lk2nd: panel: generated: fix -Wunused-variable ili9881c_hd_video_off_command

- Documentation/devices.md
- lk2nd/device/dts/msm8974/msm8974-lge-hammerhead.dts
- lk2nd/device/dts/msm8974/rules.mk
LG Nexus 5 (hammerhead) should not be added for QCDTBS list it breaks other devices. It works with ADTBS and QCDTBS list should be empty.
@z3ntu @minlexx
> doc/dts: msm8974: Remove hammerhead from qcdtbs and document the quirks

- Documentation/devices.md
- lk2nd/device/dts/msm8909/msm8909-qrd-skub.dts
- lk2nd/device/dts/msm8909/rules.mk
> Add Lenovo Yoga Tab 3 10 LTE support

- lk2nd/device/dts/msm8953/msm8953-xiaomi-daisy.dts
This PR fixes the xiaomi-daisy DTS which is misconfigured as `QCOM_BOARD_ID(MTP` instead of QCOM_BOARD_ID(QRD`.
Reference: https://github.com/msm8953-mainline/lk2nd/blob/main/dts/msm8953-xiaomi-daisy.dts#L10
> Fix xiaomi daisy dts

- .gitignore
- Documentation/dt-bindings.md
- lk2nd/device/device.c
- lk2nd/device/device.h
- lk2nd/device/dts/msm8226/apq8026-asus-sparrow.dts
- lk2nd/device/dts/msm8226/apq8026-huawei-sturgeon.dts
- lk2nd/device/dts/msm8226/apq8026-lg-lenok.dts
- lk2nd/device/menu/menu.c
Implement optional single-key navigation scheme: short keypress navigates menu items down, and a long press (>1s) selects the item.
fixes #432
@z3ntu would you mind checking that I've picked the correct smartwatches to use single-key? not sure if one of those has multiple keys...
> Add long-press navigation mode

- lk2nd/device/dts/msm8953/msm8953-huawei-milan.dts
- lk2nd/device/dts/msm8953/msm8953-lenovo-kuntao.dts
Set lk2nd,dtb-files for lenovo-kuntao and huawei-milan.
> msm8953: set more lk2nd,dtb-files

- Documentation/devices.md
- lk2nd/device/dts/msm8916/msm8216-samsung.dts
This commit adds E5 Duos (E500H) model node to the msm8216-samsung dts. Also lists the device under Documentation/devices.md.
Can't test if the panel works but another user reports that there's display already.
```
$ fastboot getvar all
....
(bootloader) lk2nd:model:Samsung Galaxy E5 (SM-E500H)
(bootloader) lk2nd:compatible:samsung,e35g
```
> dts: msm8216-samsung: add e53g

- Documentation/devices.md
- lk2nd/device/dts/msm8909/msm8909-zte-sapphire.dts
- lk2nd/device/dts/msm8909/rules.mk
I have created a basic device tree to get lk2nd booting on my zte sapphire.
Quirks: the system partition is read-only from linux.  Installing to the userdata partition worked fine
> msm8909: add support for ZTE N818s (codename: sapphire)

- Documentation/devices.md
- lk2nd/device/dts/msm8226/msm8226-samsung.dts
Add 3g variant of samsung-millet.
It based on msm8226 instead of apq8026 which used in milletwifi (SM-T330)
<details>
<summary>Pictures</summary>
Tablet running lk2nd photo
</details>
> dts: msm8226: msm8226-samsung: millet3g: new device

- lk2nd/device/dts/msm8952/msm8920-motorola-jeter.dts
- lk2nd/device/dts/msm8952/msm8937-motorola-jeter.dts
- lk2nd/device/dts/msm8952/rules.mk
Hello everyone, this pull request introduces device tree support for the Motorola Moto G6 Play (codenamed "jeter") on the MSM8952 platform, which utilizes the MSM8920 CPU (Snapdragon 427).
The DTS was handwritten based on downstream DTS extracted from [unofficial TWRP images found on XDA](https://xdaforums.com/t/g6-play-unofficial-twrp-xt1922-x.4038873/) and the [official TWRP of G6 (non-play variant)](https://twrp.me/motorola/motorolamotog6.html). Its functionality was tested and verified by @pryzhak, the device owner, via the Matrix community. The `gpio-keys` were explicitly set exactly as the downstream DTS, maybe we can strip down "down" and "power" keys after some more testing with @pryzhak.
Build command (needs bootsignature.py dependencies installed):
```bash
make …
```
> dts: msm8952: Add support for Motorola Moto G6 Play (XT1922-X, jeter)

- Documentation/building.md
- app/aboot/aboot.c
- lk2nd/project/base.mk
Useful when a kernel panic occurs before a debugger is attached
> Feature: Add optional delay before booting via `fastboot boot`

- lk2nd/device/dts/msm8953/rules.mk
motorola-potter is only booting with QCDTB.
> msm8953: motorola-potter: change to QCDTB

- lk2nd/device/dts/msm8952/msm8917-xiaomi-rolex.dts
Downstream node names was miss typed what cause panel selection not worked as expected.
> dts: msm8952: xiaomi-rolex: fix panel selection

- Documentation/devices.md
- lk2nd/device/dts/msm8952/msm8917-xiaomi-riva.dts
- lk2nd/device/dts/msm8952/msm8917-xiaomi-rolex.dts
- lk2nd/device/dts/msm8952/msm8937-mtp.dts
- lk2nd/device/dts/msm8952/msm8937-xiaomi-land.dts
- lk2nd/device/dts/msm8952/rules.mk
- lk2nd/device/dts/msm8952/sdm439-xiaomi-pine.dts
New Devices:
- SDM439 Redmi 7A (it needs custom minimal dtbo.img to work)
- MSM8937 Motorola Moto E5 Plus (MSM8940 and MSM8917 variants are not supported)
Changes:
- Remove Redmi 3S workaround documentation it is not needed anymore
- Add touchscreen-compatible for Redmi 4A and 5A
> MSM8952: Add more devices + fixes

- lk2nd/device/dts/msm8953/apq8053-lenovo-cd-18781y.dts
Commit 72e9abacf8812298851ac4c9137fceb0af56bfa4 introduced QCTD images to the MSM8953 builds.
The Lenovo ThinkSmart View (CD-18781Y) will not boot lk2nd images that are built with a QCDT image appended. Add this to the notes in the dts.
> dts: msm8953: apq8053-lenovo-cd-18781y: update note on quirks

- Documentation/dt-bindings.md
- lk2nd/device/device.c
- lk2nd/device/device.h
- lk2nd/device/dts/msm8953/apq8053-lenovo-cd-18781y.dts
- lk2nd/device/menu/menu.c
This adds a feature to specify custom key descriptions for the navigation hint in the menu.
This is mostly useful for devices that need to re-map keys, such as https://github.com/msm8916-mainline/lk2nd/blob/main/lk2nd/device/dts/msm8953/apq8053-lenovo-cd-18781y.dts
Please let me know if this creates ginormous memory leaks and security issues, as my C is certainly getting better but it's still not great. I'm aware that you'd eventually have to call `free()` on a `strdup()` but it seems this is done nowhere in the code for all the other fields of the `lk2nd_dev` struct that have something `strdup`'d into it via `lk2nd_device2nd_parse_cmdline` (for example).
Before and after, showing the incorrect key descriptions on the left device (without this patch) and the correct key descriptions on …
> menu: Add a custom menu key description feature

- Documentation/devices.md
- lk2nd/device/dts/msm8952/msm8920-mtp.dts
- lk2nd/device/dts/msm8952/rules.mk
Nora is an MTP device (even though Android DTs have different board-id, ref: [msm8917-nora-p0.dts](https://github.com/motoe5/android_kernel_motorola_msm8937/blob/lineage-17.1/arch/arm/boot/dts/qcom/msm8917-nora-p0.dts) [msm8920-nora-p0.dts](https://github.com/motoe5/android_kernel_motorola_msm8937/blob/lineage-17.1/arch/arm/boot/dts/qcom/msm8920-nora-p0.dts); same deal as #416 – maybe all these IDs should be put into the device node as in the "msm-id override" doc section) available in MSM8917 and MSM8920 variants.
upd: tianma 571 → ili9881h is the only IC i could find in [commits](https://github.com/motoe5/android_kernel_motorola_msm8937/commit/b0adda93fcc70860f9cdc1f28fa15cad8a1378c9)
> dts: msm8952: Add Motorola Moto E5 (nora)

- lk2nd/device/dts/msm8960/bundle.dts
This makes lk2nd boot functionally on the samsung-loganrelte. Screen doesn't refresh for some reason. Anything else works.
> dts: msm8960: add Samsung Galaxy Ace 3 LTE

- lk2nd/device/dts/msm8952/msm8917-mtp.dts
- lk2nd/device/dts/msm8952/msm8920-mtp.dts
We have decided not to list the IC for the only variant where we know it. (https://github.com/msm89x7-mainline/linux-panel-drivers/pull/5)
> dts: msm8952: motorola-nora: align panel compatibles with dev tree

- Documentation/devices.md
- lk2nd/device/dts/msm8916/msm8939-huawei-federer.dts
- lk2nd/device/dts/msm8916/rules.mk
> dts: msm8939: Add support for Huawei MediaPad T2 10.0 Pro (federer)

- Documentation/devices.md
- lk2nd/device/dts/msm8952/msm8917-mtp.dts
Add Motorola Moto E5 Plus (hannah) (MSM8917) Variant.
> dts: msm8952: Add Motorola Moto E5 Plus (MSM8917)

- Documentation/devices.md
- lk2nd/device/dts/msm8909/msm8909-1gb-qrd-skuc.dts
- lk2nd/display/panel/generated/lk_panel_ili9806e_fwvga_hsd_hlt_video.h
- lk2nd/display/panel/generated/panels.h
lk1st for Haier G151 (MSM8909) alongside with the panel drivers, tested working like how the stock bootloader would.
> dts: msm8909-1gb-qrd-skuc: add Haier G151

- platform/msm_shared/usb30_dwc_hw.c
Based on:
https://github.com/torvalds/linux/blob/master/drivers/usb/dwc3/core.c#L319
https://github.com/torvalds/linux/commit/f4fd84ae0765a80494b28c43b756a95100351a94
> msm_shared_ dwc: Stop device in dwc_device_reset

- lk2nd/display/panel/generated/lk_panel_boe_otm8019a_5p0_fwvga_video.h
- lk2nd/display/panel/generated/panels.h
Add a header file for the boe_otm8019a_5p0_fwvga_video panel found in the Huawei Y635-L01 smartphone.
Use the following command to build lk1st with this panel: make TOOLCHAIN_PREFIX=arm-none-eabi- lk1st-msm8916
LK2ND_BUNDLE_DTB=msm8916-huawei-y635-l01.dtb \
LK2ND_COMPATIBLE=huawei,y635-l01 \
LK2ND_DISPLAY=boe_otm8019a_5p0_fwvga_video
> lk2nd: display: panel: generated: Add boe_otm8019a_5p0_fwvga_video

- Documentation/devices.md
- lk2nd/device/dts/msm8996/msm8996-lg-h850.dts
- lk2nd/device/dts/msm8996/rules.mk
Working device tree for the LG G5 (H850, EU model.)
Confirmed that menu navigation keys work, and am able to boot a TWRP image using fastboot boot.
> Add support for LG G5 (H850)

- lk2nd/device/dts/msm8953/rules.mk
- lk2nd/device/dts/msm8953/sdm450-samsung-r04.dts
This MR is for adding support for the Samsung SM-T595 Tablet.
Status:
it boots, things like fastboot flash and fastboot boot work
Quirks: 
sometimes USB breaks, even after cold booting, sometimes i noticed it happening when a Kernel initialized usb, and going to Download mode fixed it (survives cold boots), but i can't constantly reproduce it
> msm8953: add support for Samsung Galaxy Tab A (2018, 10.5) LTE 

- lk2nd/device/2nd/rules.mk
Create a 1 byte large fake ramdisk that is just 1 zero.
Some devices (in my case Nexus 6P) will not boot a Android bootimage if the bootimage has no ramdisk in it, it can be anything any garbage or whatever just has to be present
> lk2nd: build: create a fake ramdisk

- Documentation/devices.md
- lk2nd/device/dts/msm8916/msm8916-wiko-chuppito.dts
- lk2nd/device/dts/msm8916/rules.mk
Adds support for `wiko-chuppito`.
> dts: msm8916: Add support for Wiko Pulp 4G

- lk2nd/device/panel.c
Remove failure when ts-compatible is in use and status property is missing from touchscreen node. Make a warning instead of fail.
Issues:
- Message is not appearing in the logs yet.
- Maybe it would be great show this warning on splash.
Fixes: #482
> lk2nd: device: panel: remove failure on status is missing

- lk2nd/device/dts/msm8996/msm8996-lg-h850.dts
H850 and RS988 variants have the same board-id. This DTS fully works on both, so use lk2nd,match-cmdline to just tell us which variant we're running on.
> Add device variant RS988 (US)

- Documentation/dt-bindings.md
- lk2nd/device/leds.c
- lk2nd/device/rules.mk
I use lk1st for most of the time and find it really annoying to has no LED indication in lk1st. So here is the driver to resolve the issue. The code is based on keymap.c, though much simpler and provides no API for other modules. You need to add a node to the dts like below:
```dts
leds {
compatible = "gpio-leds";
red {
gpios = <&tlmm 3 GPIO_ACTIVE_LOW>;
default-state = "on" // or "off", "keep"
};
};
```
Tested on a downstream zhihe device with lk2nd.
Not all error paths are tested yet. Need review.
> lk2nd: device: Add an LED driver

- Documentation/devices.md
- lk2nd/device/dts/msm8974/samsung.dts
These are the T-Mobile US variants of the Samsung Galaxy Note 3 and Samsung Galaxy S5.  They are functionally identical from what I can tell except have the T suffix on the bootloader name.  Tested on both, though I haven't gotten hlte to actually boot anything but I think it's related to a postmarketOS build issue (boot.img too large).  I was able to get klte to boot postmarketOS following the wiki guide.
> Add hltetmo (N900T) and kltetmo (G900T) variants

- lk2nd/device/dts/msm8916/msm8916-samsung.dts
SM-J510L is a S. Korean U+ carrier variant of SM-J510x. AFAICT no additional tweaks are needed other than just adding it as a supported device in the DTS.
There are other variants such as J510S/K (for different carriers) but this is the only hardware I have and thus have tested on.
> Add Samsung Galaxy J5 2016 U+ (SM-J510L)

- lk2nd/device/dts/msm8960/bundle.dts
This is quite an old device. It's an AT&T specific variant of the Galaxy Tab 2 10.1 that was given to me years ago and has been collecting dust so I figured it would be fun to play with.
> dts: msm8960: add Samsung Galaxy Tab 2 10.1 (SGH-I497)

- lk2nd/device/dts/msm8952/msm8917-mtp.dts
- lk2nd/device/dts/msm8952/msm8940-mtp.dts
Redmi Note 5A and 5A Prime's touch controllers are bind to the panels.
> Add touch selection for Redmi Note 5A/5A Prime

- Documentation/devices.md
- lk2nd/device/dts/msm8952/msm8952-mtp.dts
- lk2nd/device/dts/msm8952/rules.mk
Add support for msm8952 based alcatel-idol4.
Looking at some downstream, there seem to be only one panel variant.
There are 2 touchpanels declared tho, but it will take a while until that's usable, so...
> dts: msm8952: Add Alcatel Idol 4 (idol4)

- Documentation/devices.md
- lk2nd/device/dts/msm8909/apq8009-lenovo-tb-x103f.dts
- lk2nd/device/dts/msm8909/rules.mk
Basic boot testing only.
- Screen working
- Buttons working
> Add support for Lenovo Tab 10 (TB-X103F)

- dev/gcdb/display/gcdb_display.c
gcdb: display: Print framebuffer address on panel initialization
Matches cont-splash logging.
Change-Id: I62bbeef05b317dbd68af1924080bc32f3b210cfc
> gcdb: display: Print framebuffer address on panel initialization

- Documentation/devices.md
- lk2nd/device/dts/msm8909/apq8009-1gb-qrd-skue.dts
- lk2nd/device/dts/msm8909/msm8909-1gb-qrd-skue.dts
- lk2nd/device/dts/msm8909/rules.mk
Real apq8009-qrd-skue and msm8909-qrd-skue has property `qcom,board-id = <0x1000b 0x109>`.
> msm8909-1gb-qrd-skue: rename and clean up

- Documentation/devices.md
- lk2nd/device/dts/msm8916/msm8916-ee-harrier-mini.dts
- lk2nd/device/dts/msm8916/rules.mk
Based on the msm8916 board.
Currently a draft as of right now as the volume keys are inverted and defining the correct GPIOs for them (that hasn't been pushed here for the following reason) seem to not work, the volume up key will work as expected but the rest stop responding.
> lk2nd: dts: msm8916: Add EE Harrier Mini (harrier_mini)

- Documentation/devices.md
- lk2nd/device/dts/msm8960/bundle.dts
unfortunately this device has some quirks:
1. the display requires a lot of work, so for now we need ENABLE_DISPLAY=0 instead.
2. the UART on C5302 (non LTE) has serial output on gsbi8, not at gsbi5. So somehow we need a way to define this via dts?
> dts: msm8960: Add support for Sony Xperia SP (huashan)

- Documentation/devices.md
- lk2nd/device/dts/msm8610/msm8612-huawei-c8816.dts
- lk2nd/device/dts/msm8610/rules.mk
- target/msm8610/init.c
1. Make dts folder for msm8610, firstly the dts of Huawei C8816
2. Add enum const 'HW_PLATFORM_SUBTYPE_NO4 = 4' for 'qcom,board-id = <8016 4>'.
Without it, target_baseband_detect() mismatches board-subid and hits ASSERT(), causing panic / EDL:
```c
Format: Log Type - Time(microsec) - Message
Log type: B - since boot(excluding boot rom).  D - delta
B -    500627 - Error code 302a at boot_error_handler.c Line 456
BL_ERR_DATA_ABORT
```
Tested OK on all panels!
> dts: msm8610: add support for Huawei C8816

- Documentation/devices.md
- lk2nd/device/dts/msm8916/msm8916-samsung.dts
This adds support for the Verizon Wireless variant of the Samsung Galaxy Core Prime LTE (which can run unsigned images through [an exploit](https://code.chipmunk.land/chipmunkmc/rossa-vzw-tethered-exploit)).
> Add SM-G360V (coreprimeltevzw) support

- lk2nd/device/dts/msm8916/msm8939-asus-z00t.dts
The current tree is configured to only allow booting ZE551KL and not other variants of Z00T. This PR adds additional qcom,board-id and qcom,msm-id properties to include support for other variants of Z00T as well.
> Improved support for Asus ZenFone 2 Laser/Selfie (Z00T)
